development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://fpmmkymdsrelmf:1f5ab2b4ae501e60cfc1f79200ac3a5f04cff497e368895390f6062c8d65cf75@ec2-54-83-49-44.compute-1.amazonaws.com:5432/d43j0rg3nq2jg6

